# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

---
version: "2"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
      args:
        # pip versioning by default
        # Replace with local tarballs like /src/jupyter_dashboards-0.6.0.dev0.tar.gz
        DASHBOARDS_PKG: 'jupyter_dashboards==0.5.2'
        DECLWIDGETS_PKG: 'jupyter_declarativewidgets==0.5.1'
        CMS_PKG: 'jupyter_cms==0.5.0'
        BUNDLER_PKG: 'jupyter_dashboards_bundlers==0.7.0'
    volumes:
      - /home/jovyan/work
    ports:
      - "8888:8888"
    depends_on:
      - dashboards
    links:
      - dashboards
    environment:
        DASHBOARD_REDIRECT_URL: http://{hostname}:3000/
        DASHBOARD_SERVER_URL: http://dashboards:3000/
        DASHBOARD_SERVER_AUTH_TOKEN: notebook_to_dashboard_secret

  dashboards:
    build:
      context: .
      dockerfile: Dockerfile.dashboards
      args:
        # npm versioning by default
        # Replace with local source tree /src
        DASHBOARDS_SERVER_PKG: 'jupyter-dashboards-server@>=0.5.0 <0.6.0'
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      KERNEL_GATEWAY_URL: http://kernel_gateway:8888
      AUTH_TOKEN: notebook_to_dashboard_secret
      USERNAME: demo
      PASSWORD: demo

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel
      args:
        # pip versioning by default
        # Replace with local tarballs like /src/jupyter_declarativewidgets-someversion.tar.gz
        DECLWIDGETS_PKG: 'jupyter_declarativewidgets==0.5.1'
        IPYWIDGETS_PKG: 'ipywidgets==5.0'
    volumes_from:
      - notebook
    environment:
      KG_ALLOW_ORIGIN: '*'
